# Build Step
FROM golang:1.16-alpine as BUILD_STEP
LABEL maintainer="Jintae, Kim <6199@outlook.kr>"

COPY . /app
ENV HOME=/app

# Build
WORKDIR ${HOME}
RUN apk --no-cache add tzdata \
&& go build -o bin/main main.go

# Deploy Step
FROM alpine:latest

# Build Argument Set
ARG ELS_HOST=${ELS_HOST}
ARG ELS_USER=${ELS_USER}
ARG ELS_PASSWORD=${ELS_PASSWORD}
ARG ELS_INDEX=${ELS_INDEX}
ARG REDIS_HOST=${REDIS_HOST}
ARG REDIS_PORT=${REDIS_PORT}
ARG REDIS_DB=${REDIS_DB}
ARG REDIS_PASSWORD=${REDIS_PASSWORD}
ARG REDIS_KEY=${REDIS_KEY}
ARG RELATED_API=${RELATED_API}

# Env Set
ENV GIN_MODE=release
ENV PORT=8000
ENV ELS_HOST=${ELS_HOST}
ENV ELS_USER=${ELS_USER}
ENV ELS_PASSWORD=${ELS_PASSWORD}
ENV ELS_INDEX=${ELS_INDEX}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_DB=${REDIS_DB}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_KEY=${REDIS_KEY}
ENV RELATED_API=${RELATED_API}

# Timezone Set
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN mkdir /app && apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=BUILD_STEP /app/bin/main .

EXPOSE $PORT
ENTRYPOINT ["./main"]
