// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/99-66/NaiaBackendApi/controllers"
	"github.com/99-66/NaiaBackendApi/repositories"
	"github.com/99-66/NaiaBackendApi/services"
	"github.com/elastic/go-elasticsearch/v7"
)

// Injectors from wire.go:

func initWINApi(es *elasticsearch.Client) controllers.WINApi {
	winRepository := repositories.ProvideWINRepository(es)
	winService := services.ProvideWINService(winRepository)
	winApi := controllers.ProvideWINApi(winService)
	return winApi
}
