#!/bin/bash
set -ex

# DockerHub Automated Build를 위한 Custom Environment Hook
# 빌드 시에 사용자 환경변수를 전달한다

docker build \
    --build-arg ELS_HOST="${ELS_HOST}" \
    --build-arg ELS_USER="${ELS_USER}" \
    --build-arg ELS_PASSWORD="${ELS_PASSWORD}" \
    --build-arg ELS_INDEX="${ELS_INDEX}" \
    --build-arg REDIS_HOST="${REDIS_HOST}" \
    --build-arg REDIS_PORT="${REDIS_PORT}" \
    --build-arg REDIS_DB="${REDIS_DB}" \
    --build-arg REDIS_PASSWORD="${REDIS_PASSWORD}" \
    --build-arg REDIS_KEY="${REDIS_KEY}" \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
