basePath: /api/1
definitions:
  config.APIError:
    properties:
      error:
        type: string
    type: object
  models.WinList:
    properties:
      count:
        type: integer
      word:
        type: string
    type: object
  models.WinTag:
    properties:
      percent:
        type: number
      tag:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: WhatIssueNow Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: WhatIssueNow API
  version: "1.0"
paths:
  /list:
    get:
      consumes:
      - application/json
      description: 현재시간 기준 3시간 전까지의 상위 이슈 단어 30개를 반환한다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WinList'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.APIError'
      summary: 이슈 단어목록 API
      tags:
      - WhatIssueNow
  /stopwords:
    get:
      consumes:
      - application/json
      description: ElasticSearch 집계시에 제외되는 불용어 목록을 반환한다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.APIError'
      summary: 불용어 단어목록 API
      tags:
      - StopWords
  /tag/{word}:
    get:
      consumes:
      - application/json
      description: 특정 단어의 발생지(태그) 점유율을 반환한다
      parameters:
      - description: Word
        in: path
        name: word
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WinTag'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.APIError'
      summary: 단어별 태그 점유율 API
      tags:
      - WhatIssueNow
schemes:
- http
- https
swagger: "2.0"
