basePath: /api/1
definitions:
  libs.APIError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  win_m.WList:
    properties:
      count:
        type: integer
      word:
        type: string
    type: object
  win_m.WTag:
    properties:
      percent:
        type: number
      tag:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: 6199@outlook.kr
    name: Jintae, kim
    url: http://whatissuenow.com
  description: WhatIssueNow Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: WhatIssueNow API
  version: "1.1"
paths:
  /list:
    get:
      consumes:
      - application/json
      description: 현재시간 기준 3시간 전까지의 상위 이슈 단어 30개를 반환한다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/win_m.WList'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/libs.APIError'
      summary: 이슈 단어목록 API
      tags:
      - WhatIssueNow
  /stopwords:
    get:
      consumes:
      - application/json
      description: ElasticSearch 집계시에 제외되는 불용어 목록을 반환한다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/libs.APIError'
      summary: 불용어 단어목록 API
      tags:
      - StopWords
  /tag/{word}:
    get:
      consumes:
      - application/json
      description: 특정 단어의 발생지(태그) 점유율을 반환한다
      parameters:
      - description: Word
        in: path
        name: word
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/win_m.WTag'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/libs.APIError'
      summary: 단어별 태그 점유율 API
      tags:
      - WhatIssueNow
  /wordcloud:
    get:
      consumes:
      - application/json
      description: 현재시간 기준 3시간 전까지의 상위 이슈 단어 60개를 반환한다
      parameters:
      - description: 워드클라우드 단어 개수(최대 100개)
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                type: object
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/libs.APIError'
      summary: 워드 클라우드를 위한 이슈 단어목록 API
      tags:
      - WhatIssueNow
schemes:
- http
- https
swagger: "2.0"
